config/routes.rb
Rails.application.routes.draw do
  resources :songs
  devise_for :users
  root 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
    validates :title, presence: true
    validates :artist, presence: true
    validates :genre, presence: true
    validates :youtube_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
       @songs = Song.all
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:artist, :title, :genre, :youtube_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pulse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<center>
<div class="page header" style="max-width: 400px">
    <h1>Pulse</h1>
    <%= link_to 'New Song', new_song_path, class: "btw btw-primary btn-lg" %>
</div>

<div class="list-group" style="max-width: 400px">
  <% @songs.each do |song| %>
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>

    <%= link_to 'View All Songs', songs_path, class: "btw btw-primary btn-lg" %>


</center>

app/views/shared/_navbar.html.erb
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Pulse', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li class="dropdown">
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% else %>
        <li><%= link_to 'Add track', new_song_path %></li>
        <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
            <li><a href="#">View Profile</a></li>
            <li><a href="#">Edit Profile</a></li>
            <li><a href="#">Favorites</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" style="max-width: 400px">
    <h5>Title:</h5>
    <%= form.text_field :title, class: "form-controll input-lg" %>
  </div>

  <div class="form-group" style="max-width: 400px">
    <h5>Artist:</h5>
    <%= form.text_field :artist, class: "form-controll input-lg" %>
  </div>

  <div class="form-group" style="max-width: 400px">
    <h5>Genre</h5>
    <%= form.select :genre,  [
                                 ["Alt.Rock", "Alt.Rock"],
                                 ["Acoustic", "Acoustic"],
                                 ["Ambiance", "Ambiance"],
                                 ["Electronic", "Electronic"],
                                 ["Future house", "Future house"],
                                 ["Future bass", "Future bass"],
                                 ["Trap", "Trap"],
                                 ["Electro house", "Electro house"],
                                 ["Prog. house", "Prog. house"],
                                 ["Rock", "Rock"],
                                 ["Dubstep", "Dubstep"],
                                 ["Deep house", "Deep house"]
                                 ].sort, prompt: "Select Genre...", id: :song_genre %>
  </div>

  
  <div class="form-group" style="max-width: 400px">
    <h5>Youtube ID (Full youtube link)</h5>
    <%= form.text_field :youtube_id, class: "form-controll input-lg" %>
  </div>

  <div class="actions">
    <%= form.submit 'Post Song' %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pulse</h1>

<div class="list-group">
  <% @songs.each do |song| %>
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h3><%= @song.title %> - <%= @song.artist %> (<%= @song.genre %>)</h3>
  <div class="container">
    <iframe src="//www.youtube.com/embed/<%= @song.youtube_id.gsub("https://www.youtube.com/watch?v=", "") %>" 
    frameborder="0" allowfullscreen class="video"></iframe>
  </div>
</div>

<%= link_to 'Back', songs_path %>